typography_spectrum: 0.32337257374557526
color:
  brandStrength: 0.7135447998451862
  lightness: 0.639443493400894
  saturation: 0.2768743282947505
  rhythmicContrast: 0.37088209979291453
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/be0fa10a-69a0-481e-b782-35d4f90e00e9.jpg
layout_spectrum: 0.20771623953835727
author:
  name: George Christodoulou Jagaro & Magdalena Manta Hotoleanu
  email: george.christodoulou@athinaionfos.gr
  url: 'http://about-us.athinaionfos.gr'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/222e5783-00a9-4007-80d2-4e3d3ee22fe9.png
name: Thai Massage Romania
url: 'http://thaimassage.education'
navigation:
  - name: 'Αρχική '
    id: 332be0a9-8b4c-4213-b51b-c94faa321242
    type: content
  - name: About Us
    id: 3deb5e01-48ec-4fc0-b92b-4f4096059d62
    type: content
  - name: Αθηναίων Φως
    url: 'http://athinaionfos.gr'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c7415ab-ce51-45e9-9790-fc31c73ce3d7.png
title: Advanced Therapeutic Thai Massage
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fe9d8cb-4fbe-4cba-8e39-554f25c9d9c1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fe9d8cb-4fbe-4cba-8e39-554f25c9d9c1.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Healing the physical body and bring joy to the mind
purpose:
  - type: contact
    url: 'tel:+40743873349'
    label: Call Us
  - type: contact
    url: 'mailto:magalena.hotoleanu@gmail.com'
    label: Contact Us
